version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: open_wallet
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: abcd1234
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"